# 데이터 경로 설정
paths:
  # 임베딩 DB가 저장된 디렉토리 경로
  output_dir: "./artifacts/travel_DB"

  # 메타데이터 CSV 파일 경로
  custom_metadata_csv: './trip/metadata.csv'
  
  # 이미지 파일의 루트 디렉토리
  custom_image_root: './'

# 모델 설정
model:
  # Hugging Face 모델 ID
  model_id: 'google/siglip2-base-patch16-384'
  
  # 파인튜닝된 모델 가중치 경로(필요 시 지정)
  finetuned_path: "./artifacts/models/trip_recommend.pt"

# 시스템 설정
system:
  device: 'cpu'
