# --- 프로젝트 전반에 사용될 경로 설정 ---
paths:
  # 생성된 DB 및 모델 가중치를 저장할 출력 디렉토리
  output_dir: "/home/workspace/artifacts/travel_DB"

  # --- 커스텀 데이터셋 설정 ---
  # 1. 메타데이터 CSV 파일 경로
  custom_metadata_csv: '/home/workspace/data/database/total_metadata.csv' # 실제 CSV 파일 경로로 수정
  
  # 2. 이미지 파일의 루트 디렉토리
  #    (CSV의 경로가 '/home/...' 같은 절대 경로이면 이 값을 "" 빈 문자열로 두세요)
  #    (CSV의 경로가 'database/korea/...' 같은 상대 경로이면, 그 앞의 루트 경로를 적으세요)
  custom_image_root: '/home/workspace/data' # 예: '/home/workspace/'

# --- 모델 관련 설정 ---
model:
  # 사용할 모델명(Hugging Face 모델 허브 기준)
  model_id: 'google/siglip2-base-patch16-384'
  
  # 파인튜닝된 모델 가중치 (없으면 null)
  finetuned_path: "/home/workspace/artifacts/models/finetuned_google_siglip2-base-patch16-384_final.pt"

# --- 시스템 설정 ---
system:
  device: 'cpu'
