# --- 프로젝트 전반에 사용될 경로 설정 ---
paths:
  # 생성된 DB 및 모델 가중치를 저장할 출력 디렉토리
  output_dir: "/home/workspace/output_custom_db"

  # --- 커스텀 데이터셋 설정 ---
  # 1. 메타데이터 CSV 파일 경로
  custom_metadata_csv: '/home/workspace/data/database/total_metadata.csv' # (중요) 실제 CSV 파일 경로로 수정
  
  # 2. 이미지 파일의 루트 디렉토리
  #    (CSV의 경로가 '/home/...' 같은 절대 경로이면 이 값을 "" 빈 문자열로 두세요)
  #    (CSV의 경로가 'database/korea/...' 같은 상대 경로이면, 그 앞의 루트 경로를 적으세요)
  custom_image_root: '/home/workspace/data' # 예: '/home/workspace/'

# --- 커스텀 데이터셋 컬럼 설정 ---
custom_dataset_columns:
  # CSV에서 실제 이미지 파일 경로가 포함된 컬럼 이름
  image_path_column: 'directory'
  
  # Faiss ID에 매핑할 고유한 '문자열' ID가 포함된 컬럼 이름
  # (경로 자체가 고유 ID이므로 'directory' 사용, 'title'도 가능)
  unique_id_column: 'directory' 

# --- 모델 관련 설정 ---
model:
  # 사용할 모델 (CLIP 또는 SigLIP)
  model_id: 'google/siglip2-base-patch16-384'
  
  # 파인튜닝된 모델 가중치 (없으면 null)
  finetuned_path: "/home/workspace/output/new_dataset/SigLIP2/train_clean_dali_epoch5/finetuned_google_siglip2-base-patch16-384_final.pt"

# --- 검색(Retrieval) 관련 설정 ---
retrieval:
  batch_size: 32
  use_amp: false

# --- 시스템 설정 ---
system:
  device: 'cpu'
  num_workers: 4
